### PR TITLE
Feature/execute js cli plugin

### PR DESCRIPTION
**Pull request by arxpoetica**
We plan on using this, but thought we'd do a PR since it's probably a common need. Let me know if there needs to be changes.

### CODE REVIEW

**Comment by arxpoetica** [comment]
Overview: this pull request enables execution of js code via plugins. The default plugin listens for a global variable `window.ATHENA_PDF_READY` to be present on the page before rendering a PDF file. Note that any `athena.delay` will still be applied after the js is ready. Let me know if there are any questions.

**Comment by arxpoetica** [comment]
Thoughts?

**Comment by hazzadous** [comment]
We're planning on a reasonably large rewrite that will include a feature like this. We'd rather not merge this in given that it's quite a large change to the underlying behaviour and we currently do not have any tests.

The rewrite is happening here: https://github.com/arachnys/athenapdf/tree/cdp

**Comment by arxpoetica** [comment]
Okay. I think we're going to start using headless Chrome in any case. If not we'll just keep using our branch until your rewrite is done.

**Comment by MrSaints** [comment]
Yes @arxpoetica, the plan is to ditch Electron. At the end of the day, we only used it for the high-level APIs, and for Chromium's rendering. Now that Chromium headless is out, and there is a nice API for it, I think the plan is to move entirely to it. Nevertheless, thank you so much for your PR.

**Comment by MrSaints** [comment]
It is now possible to run a combination of custom, and built-in JavaScript _plugins_ in v3.

**Comment by arxpoetica** [comment]
@danadams FYI

**Comment by arxpoetica** [comment]
@mrdanadams FYI, maybe let the team know ^^^

**Comment by bploetz** [comment]
@arxpoetica 👍 thanks

**Pull request closed without merging**
