### PR TITLE
Add option to ignore cert errors

### PR DESCRIPTION
**Pull request by lanceulmer**

### CODE REVIEW

**Comment by leosprikryl** [comment]
Is there anything I could do to help to have this merged? It is a really simple change and it works well on my side. I would prefer not make my own custom docker image just because of this.

**Comment by MrSaints** [comment]
@lanceulmer @leosprikryl Apologies for the delay. It looks good to me.

I think in the long term, we should make it easier to just define the 'switches' on runtime. I don't think there's much value in having them hardcoded.

**Comment by leosprikryl** [comment]
@MrSaints Thanks a lot. I agree that it would make sense to allow defining switches on runtime. That would be much more flexible solution. Unfortunately, I am not familiar with Go, so I can't help with that.

**Comment by MrSaints** [comment]
@leosprikryl No worries. This is on the JavaScript side. Feel free to have a look :)

**Pull request merged**
