### PR TITLE
Proxy Support

### LINKED ISSUE #5: Proxy Support
AthenaPDF looks amazing! Can't wait to give it a try, but need to fetch HTML remotely via proxy. Any planned support for this?

### PR DESCRIPTION
**Pull request by zohararad**
Added CLI arg to support loading remote URL via proxy. resolves #5

### CODE REVIEW

**Comment by MrSaints** [comment]
Silly question, but I'm assuming you've tested it?

I'll look into it 👍

**Comment by zohararad** [comment]
I tested it by running athena CLI with a public anonymous proxy against http://www.whatismyip.com and it worked fine. I did notice there's no way to pass proxy login details to Electron. Otherwise it seems to work OK.

I didn't see a test suite in the code to run tests with. Did I miss it?

**Comment by MrSaints** [comment]
Correct me if I'm wrong, I do believe you can pass auth credentials through: `--proxy-server="username:password@address:port"` (https://www.chromium.org/developers/design-documents/network-settings#TOC-Command-line-options-for-proxy-settings)

And yea, we do not have a test suite ATM.

**Comment by zohararad** [comment]
No... tried that and it failed miserably. You usually define proxy auth credentials separately or when prompted.

**Comment by MrSaints** [comment]
Sorry for the late response, but I just realised that we're using the same short flag `-p` for proxy, and for the page size (albeit, the difference in casing).

I'm not sure what we can replace it with, but it might just be worth omitting it (the shorthand) since [IMHO] it's not an option that is used often. What are your thoughts @zohararad?

**Comment by zohararad** [comment]
@MrSaints make sense. Dropped it from the code.

**Comment by MrSaints** [comment]
Superb! :+1: Thanks a lot, and sorry for the delay in getting this out.

**Pull request merged**
